development:
  adapter: mysql2
  database: eve-production_dev
  username: dev
  password: dev
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: eve-production_test
  username: dev
  password: dev
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
